packages:
  - packages/*
  - tools/*
  - apps/*
  - packaging/*

patchedDependencies:
  '@aas-core-works/aas-core3.0-typescript@1.0.5': patches/@aas-core-works__aas-core3.0-typescript@1.0.5.patch
  jsqr@1.4.0: patches/jsqr@1.4.0.patch
