#!/usr/bin/env node
/**
 * Dev-only. Downloads the four font files at a pinned commit of google/fonts, verifies their
 * sha256, subsets them to WOFF2 with pyftsubset (via uv) and writes src/fonts/PROVENANCE.md.
 * Never runs at install or runtime; the WOFF2 output is committed.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Pinned commit of https://github.com/google/fonts; the blob SHAs below were verified against
// the GitHub contents API on 2026-09-10.
const COMMIT = process.env.GOOGLE_FONTS_COMMIT ?? '8e44913e4ff26fc997e6856c1ec40ff4791c98c5';
const RAW = `https://raw.githubusercontent.com/google/fonts/${COMMIT}`;
const OUT = fileURLToPath(new URL('../src/fonts/', import.meta.url));

const FONTS = [
  {
    out: 'space-grotesk.woff2',
    path: 'ofl/spacegrotesk/SpaceGrotesk[wght].ttf',
    family: 'Space Grotesk',
    licence: 'OFL-1.1',
    gitBlob: 'a1b2e6c26093066510a31147e7aec9abdc8d6c5e',
  },
  {
    out: 'space-mono-regular.woff2',
    path: 'ofl/spacemono/SpaceMono-Regular.ttf',
    family: 'Space Mono',
    licence: 'OFL-1.1',
    gitBlob: '1cfa3653dc8ddb7aa9f4ef1c9c581e9516137e6e',
  },
  {
    out: 'space-mono-bold.woff2',
    path: 'ofl/spacemono/SpaceMono-Bold.ttf',
    family: 'Space Mono',
    licence: 'OFL-1.1',
    gitBlob: '2c4f2682f915d988e7314544ff7c9e38c8c733f5',
  },
  {
    out: 'doto.woff2',
    path: 'ofl/doto/Doto[ROND,wght].ttf',
    family: 'Doto',
    licence: 'OFL-1.1',
    gitBlob: 'ed8f0db9fb890c570b558941201d1504483f5ebc',
  },
];

// Latin, Latin-1 Supplement, Latin Extended-A, general punctuation, euro, arrows and the glyphs
// the shell draws (· ▸ ▾ ✕ ⤢).
const UNICODES =
  'U+0000-00FF,U+0100-017F,U+2010-2027,U+2030-205E,U+20AC,U+2190-2199,U+2212,U+00B7,U+25B8,U+25BE,U+2715,U+2922';

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');
const gitBlobSha = (buf) =>
  createHash('sha1').update(`blob ${buf.length}\0`).update(buf).digest('hex');

mkdirSync(OUT, { recursive: true });
const rows = [];
for (const f of FONTS) {
  const url = `${RAW}/${f.path}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const ttf = Buffer.from(await res.arrayBuffer());
  const blob = gitBlobSha(ttf);
  if (blob !== f.gitBlob) throw new Error(`${f.path}: git blob ${blob}, expected ${f.gitBlob}`);
  const tmp = join(tmpdir(), `passwerk-${f.out}.ttf`);
  writeFileSync(tmp, ttf);
  const outPath = join(OUT, f.out);
  execFileSync(
    'uv',
    [
      'tool',
      'run',
      '--from',
      'fonttools[woff]',
      'pyftsubset',
      tmp,
      `--unicodes=${UNICODES}`,
      '--flavor=woff2',
      '--layout-features=*',
      '--no-hinting',
      '--desubroutinize',
      `--output-file=${outPath}`,
    ],
    { stdio: 'inherit' },
  );
  const woff2 = readFileSync(outPath);
  rows.push(
    `| \`${f.out}\` | ${f.family} | [${f.path}](${url}) | \`${COMMIT}\` / blob \`${f.gitBlob}\` | \`${sha256(ttf)}\` | \`${sha256(woff2)}\` | ${f.licence} |`,
  );
  console.log(`${f.out}: ${woff2.length} bytes`);
}
writeFileSync(
  join(OUT, 'PROVENANCE.md'),
  `# Provenance of bundled fonts

Generated by \`apps/web/scripts/fonts.mjs\` on ${new Date().toISOString().slice(0, 10)}. The fonts are
subsetted (${UNICODES}) to WOFF2 and inlined into the single-file workbench; nothing is fetched at
runtime (\`apps/web/test/fonts.test.ts\` verifies the files offline on every test run). All four
are licensed under the SIL Open Font License 1.1 (\`OFL.txt\` beside each source file).

| File | Family | Source | Ref | sha256 (download) | sha256 (woff2) | Licence |
|---|---|---|---|---|---|---|
${rows.join('\n')}
`,
);
