/**
 * Renders docs/KB_REVIEW.md: every knowledge-base attribute marked `verify: true`, with the
 * joins a domain expert has to confirm (DIN row, Commission data point, template element,
 * legal references, applicability) and an empty decision column per entry. Data only, no
 * new claims: everything shown is read from the bundled knowledge base. Deterministic.
 *
 *   pnpm --filter @passwerk/rules run review-sheet
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type Attribute, attributes, BATTERY_CATEGORIES } from '../src/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
export const REVIEW_SHEET_PATH = join(here, '..', '..', '..', 'docs', 'KB_REVIEW.md');

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const list = (xs: readonly string[]) => (xs.length === 0 ? '(none)' : xs.map(cell).join('<br>'));

function rangeText(a: Attribute): string {
  if (!a.range) return '';
  return `${a.range.min ?? '-inf'} .. ${a.range.max ?? 'inf'}`;
}

function entry(a: Attribute): string[] {
  const L: string[] = [];
  L.push(`### \`${a.id}\`: ${cell(a.name.en)} / ${cell(a.name.de)}`);
  L.push('');
  L.push('| Field | Value |');
  L.push('|---|---|');
  L.push(
    `| Value kind / unit / range | ${a.valueKind} / ${a.unit ?? '(none)'} / ${rangeText(a) || '(none)'} |`,
  );
  L.push(
    `| DIN DKE SPEC 99100 row | no. ${a.din.no}, chapter ${a.din.chapter}, category "${cell(a.category)}" |`,
  );
  L.push(
    `| Commission data points | ${a.ec.length === 0 ? '(none; applicability from override)' : a.ec.map((e) => String(e.number)).join(', ')} |`,
  );
  L.push(`| Legal references (joined) | ${list(a.legalRefs)} |`);
  L.push(`| IDTA 02035 part / template paths | ${a.part ?? '(none)'} / ${list(a.templatePaths)} |`);
  L.push(
    `| Template semanticIds (joined) | ${list(a.templateElements.map((e) => e.semanticId ?? '(no semanticId)'))} |`,
  );
  L.push(
    `| Applicability (${a.applicabilitySource}) | ${BATTERY_CATEGORIES.map((c) => `${c}: ${a.applicability[c].status}`).join('<br>')} |`,
  );
  L.push(`| Last verified | ${a.lastVerified} |`);
  L.push('');
  L.push(`**Explanation (en):** ${cell(a.explanation.en)}`);
  L.push('');
  L.push(`**Erklärung (de):** ${cell(a.explanation.de)}`);
  L.push('');
  L.push('**Reviewer decision:** [ ] confirm as is  [ ] change (state what)  [ ] remove');
  L.push('');
  L.push('**Reviewer notes:**');
  L.push('');
  return L;
}

export function renderReviewSheet(all: readonly Attribute[] = attributes): string {
  const flagged = all
    .filter((a) => a.verify)
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const L: string[] = [];
  L.push('# Knowledge-base review sheet: entries marked `verify: true`');
  L.push('');
  L.push(
    'Generated by `pnpm review-sheet` from `packages/rules/kb/attributes/*.json`. Do not edit by hand;',
    'a test fails when this file is stale. Record decisions in the JSON (set `verify: false` and',
    'bump `lastVerified`, or change the entry) and regenerate.',
  );
  L.push('');
  L.push('## What "verify" means');
  L.push('');
  L.push(
    'An attribute is flagged when the join between the DIN DKE SPEC 99100 longlist row, the',
    'Commission data point and the IDTA 02035 template element was a judgement call by the author',
    '(`packages/rules/kb/attributes/README.md`). Nothing below is a new legal or technical claim:',
    'every legal reference and semanticId is read from the bundled artefacts. The question for the',
    'reviewer is only whether the **joins** are right and whether the plain-language explanation is',
    'faithful. This sheet is not legal advice.',
  );
  L.push('');
  L.push(`## Summary: ${flagged.length} of ${all.length} attributes flagged`);
  L.push('');
  L.push('| Attribute | Name (en) | Part | DIN row | EC data points | Applicability source |');
  L.push('|---|---|---|---|---|---|');
  for (const a of flagged) {
    L.push(
      `| \`${a.id}\` | ${cell(a.name.en)} | ${a.part ?? '-'} | ${a.din.no} | ${a.ec.length === 0 ? '-' : a.ec.map((e) => String(e.number)).join(', ')} | ${a.applicabilitySource} |`,
    );
  }
  L.push('');
  L.push('## Entries');
  L.push('');
  for (const a of flagged) L.push(...entry(a));
  return `${L.join('\n')}\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sheet = renderReviewSheet();
  writeFileSync(REVIEW_SHEET_PATH, sheet);
  console.log(
    `wrote ${REVIEW_SHEET_PATH} (${attributes.filter((a) => a.verify).length} flagged entries)`,
  );
}
