import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeCsv1252, writeCsvUtf8 } from '../writers/csv.js';
import { writeDocx } from '../writers/docx.js';
import { writePdf } from '../writers/pdf.js';
import { writeXlsx } from '../writers/xlsx.js';
import * as h from './content.js';

export const HELDOUT_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..',
  '..',
  'packages',
  'core',
  'test',
  'fixtures',
  'heldout',
);

/** The manifest committed next to the documents, so core tests need no import from tools. */
export interface HeldoutManifest {
  $comment: string;
  accessed: string;
  sources: h.HeldoutSource[];
  files: h.HeldoutFile[];
  expected: h.ExpectedMapping[];
}

export function heldoutManifest(): HeldoutManifest {
  return {
    $comment:
      'Held-out evaluation set (ADR D-024). Labels and values are transcribed verbatim from the public datasheets in `sources`; layouts are re-typeset by tools/fixtures/src/heldout. Generated by `pnpm heldout`; do not edit by hand.',
    accessed: h.ACCESSED,
    sources: h.SOURCES,
    files: h.FILES,
    expected: h.EXPECTED,
  };
}

export async function generateHeldout(): Promise<Record<string, Uint8Array>> {
  return {
    'eve-lf280k-fundamental-parameters.csv': writeCsvUtf8(h.EVE_ROWS),
    'byd-battery-box-premium-hvs.xlsx': writeXlsx([
      { name: 'HVS 5.1', rows: h.BYD_HVS_5_1 },
      { name: 'HVS & HVM', rows: h.BYD_COMMON },
    ]),
    'tesvolt-ts-i-hv-80-e.pdf': await writePdf({ title: h.TESVOLT_TITLE, kv: h.TESVOLT_LINES }),
    'ampere-storage-datenblatt.docx': writeDocx(h.AMPERE_PARAGRAPHS, h.AMPERE_TABLE, null),
    'webasto-standard-battery-pro-40.txt': new TextEncoder().encode(
      `${['Standard Battery Pro 40', ...h.WEBASTO_LINES.map(([k, v]) => `${k}  ${v}`)].join('\n')}\n`,
    ),
    'bosch-powertube-750-haendlerdaten.csv': writeCsv1252(h.BOSCH_ROWS),
    'expected.json': new TextEncoder().encode(`${JSON.stringify(heldoutManifest(), null, 2)}\n`),
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  mkdirSync(HELDOUT_DIR, { recursive: true });
  const files = await generateHeldout();
  for (const [name, bytes] of Object.entries(files)) writeFileSync(join(HELDOUT_DIR, name), bytes);
  console.log(`wrote ${Object.keys(files).length} held-out files to ${HELDOUT_DIR}`);
}
