/**
 * Extracts the Battery Pass "Data attribute longlist" sheet from the bundled xlsx into a flat
 * JSON array. Pure function over the file bytes; no I/O. Uses a minimal OOXML reader (fflate +
 * regex) so the dev toolchain does not need a spreadsheet library.
 *
 * Source: Battery Pass consortium, Battery Passport Data Attribute Longlist v1.2 (January 2025),
 * CC-BY-4.0, artefacts/batterypass/2025_Battery_Passport_Data_Attributes_V1.2.xlsx
 */
import { strFromU8, unzipSync } from 'fflate';
import type { Longlist, LonglistRow } from '../../src/types.ts';

export type { Longlist, LonglistRow };

const SHEET_NAME = 'Data attribute longlist_v1.2';

const COLUMNS = {
  B: 'no',
  C: 'dinChapter',
  D: 'ev',
  E: 'lmt',
  F: 'industrialOther',
  G: 'stationary',
  H: 'category',
  I: 'subCategory',
  J: 'attribute',
  K: 'definition',
  L: 'requirementsRegulation',
  M: 'requirementsDin',
  N: 'regulationRef',
  O: 'unit',
  P: 'dataFormat',
  Q: 'accessRights',
  R: 'staticDynamic',
  S: 'updateRequirement',
  T: 'granularityModelVsIndividual',
  U: 'pack',
  V: 'module',
  W: 'cell',
} as const;

const unescapeXml = (s: string): string =>
  s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d: string) => String.fromCodePoint(Number(d)))
    .replace(/&amp;/g, '&');

const textOf = (xml: string): string =>
  unescapeXml([...xml.matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map((m) => m[1] ?? '').join(''))
    .replace(/\r\n/g, '\n')
    .trim();

export function extractLonglist(bytes: Uint8Array): Longlist {
  const files = unzipSync(bytes);
  const read = (name: string): string => {
    const entry = files[name];
    if (!entry) throw new Error(`xlsx: missing ${name}`);
    return strFromU8(entry);
  };

  const sharedStrings = [...read('xl/sharedStrings.xml').matchAll(/<si>([\s\S]*?)<\/si>/g)].map(
    (m) => textOf(m[1] ?? ''),
  );

  const workbook = read('xl/workbook.xml');
  const sheet = [...workbook.matchAll(/<sheet\b[^>]*\bname="([^"]+)"[^>]*\br:id="([^"]+)"/g)].find(
    (m) => unescapeXml(m[1] ?? '') === SHEET_NAME,
  );
  if (!sheet) throw new Error(`xlsx: sheet "${SHEET_NAME}" not found`);
  const rels = read('xl/_rels/workbook.xml.rels');
  const target = [
    ...rels.matchAll(/<Relationship\b[^>]*\bId="([^"]+)"[^>]*\bTarget="([^"]+)"/g),
  ].find((m) => m[1] === sheet[2])?.[2];
  if (!target) throw new Error('xlsx: sheet relationship not found');
  const sheetXml = read(`xl/${target.replace(/^\/?xl\//, '').replace(/^\//, '')}`);

  const rows = new Map<number, Record<string, string>>();
  for (const row of sheetXml.matchAll(/<row\b[^>]*\br="(\d+)"[^>]*>([\s\S]*?)<\/row>/g)) {
    const cells: Record<string, string> = {};
    for (const cell of (row[2] ?? '').matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)) {
      const attrs = cell[1] ?? '';
      const column = /\br="([A-Z]+)\d+"/.exec(attrs)?.[1];
      if (!column) continue;
      const type = /\bt="(\w+)"/.exec(attrs)?.[1];
      const body = cell[2] ?? '';
      let value = '';
      if (type === 'inlineStr') value = textOf(body);
      else {
        const v = /<v>([\s\S]*?)<\/v>/.exec(body)?.[1] ?? '';
        value = type === 's' && v !== '' ? (sharedStrings[Number(v)] ?? '') : unescapeXml(v);
      }
      cells[column] = value.replace(/\r\n/g, '\n').trim();
    }
    rows.set(Number(row[1]), cells);
  }

  const header = rows.get(6);
  if (header?.['J'] !== 'Attribute' || header['C'] !== 'DIN DKE Spec 99100 Chapter') {
    throw new Error(`xlsx: unexpected header row: ${JSON.stringify(header)}`);
  }

  const out: LonglistRow[] = [];
  for (const rowNumber of [...rows.keys()].sort((a, b) => a - b)) {
    if (rowNumber < 7) continue;
    const c = rows.get(rowNumber) ?? {};
    if (!c['J']) continue;
    const get = (col: keyof typeof COLUMNS): string => c[col] ?? '';
    out.push({
      no: Number(get('B')),
      dinChapter: get('C'),
      applicability: {
        ev: get('D'),
        lmt: get('E'),
        industrialOther: get('F'),
        stationary: get('G'),
      },
      category: get('H'),
      subCategory: get('I'),
      attribute: get('J'),
      definition: get('K'),
      requirementsRegulation: get('L'),
      requirementsDin: get('M'),
      regulationRef: get('N'),
      unit: get('O'),
      dataFormat: get('P'),
      accessRights: get('Q'),
      staticDynamic: get('R'),
      updateRequirement: get('S'),
      granularityModelVsIndividual: get('T'),
      granularity: { pack: get('U'), module: get('V'), cell: get('W') },
    });
  }
  return {
    $comment:
      'GENERATED by scripts/extract-longlist.ts from artefacts/batterypass/2025_Battery_Passport_Data_Attributes_V1.2.xlsx (Battery Pass consortium, CC-BY-4.0). Do not edit. Applicability: x = mandatory per Batteries Regulation, o = voluntary, empty = not applicable to that category.',
    sheet: SHEET_NAME,
    rows: out,
  };
}
