/**
 * Renders PROVENANCE.md from artefacts/manifest.json. Pure function.
 */
import type { ArtefactManifest } from '../../src/types.ts';

export function renderProvenance(manifest: ArtefactManifest): string {
  const lines: string[] = [];
  lines.push('# Provenance of bundled artefacts');
  lines.push('');
  lines.push(
    '<!-- GENERATED by scripts/generate.ts from artefacts/manifest.json. Do not edit by hand. -->',
  );
  lines.push('');
  lines.push(
    `Every third-party file in \`packages/rules/artefacts/\` is listed here with its immutable source URL, version and sha256. \`pnpm artefacts\` re-downloads and verifies them; \`test/artefacts.test.ts\` verifies the bundled files offline on every test run. Retrieved: ${manifest.retrievedAt}.`,
  );
  lines.push('');
  lines.push('## Sources and licences');
  lines.push('');
  lines.push('| Key | Source | Ref | Licence |');
  lines.push('|---|---|---|---|');
  for (const [key, s] of Object.entries(manifest.sources)) {
    const repo = s['repository'] ?? '';
    const ref = s['ref'] ?? '';
    lines.push(
      `| \`${key}\` | ${s['name'] ?? ''} (${s['publisher'] ?? ''}) — ${repo} | ${ref} | ${s['license'] ?? ''} |`,
    );
  }
  lines.push('');
  lines.push('## Artefacts');
  lines.push('');
  lines.push('| Id | Title | Version | Bundled path | Bytes | sha256 |');
  lines.push('|---|---|---|---|---|---|');
  for (const a of manifest.artefacts) {
    const path = a.path === null ? '_not bundled (checksum only)_' : `\`${a.path}\``;
    lines.push(
      `| \`${a.id}\` | [${a.title}](${a.url}) | ${a.version} | ${path} | ${a.bytes} | \`${a.sha256}\` |`,
    );
  }
  lines.push('');
  lines.push('## Not bundled on purpose');
  lines.push('');
  lines.push(
    '- **DIN DKE SPEC 99100:2025-02** (Requirements for data attributes of the battery passport) is a paid publication and is not redistributed. Chapter references in the knowledge base come from the Battery Pass Data Attribute Longlist v1.2, which the consortium published under CC-BY-4.0 and which cites the chapters.',
  );
  lines.push(
    '- **Regulation (EU) 2023/1542** and its amending acts are cited by CELEX/ELI (see `kb/timeline.json`); the consolidated text is public on EUR-Lex and is not copied into the package.',
  );
  lines.push(
    '- The **IDTA specification PDFs** are recorded above with checksums for reference but not bundled; the machine-readable JSON and AASX files are.',
  );
  lines.push(
    '- **GS1 Digital Link URI syntax** and **ISO/IEC 15459** are not bundled. The carrier module builds `/01/{gtin14}/21/{serial}` and `/8004/{giai}` URIs from the patterns in `kb/carrier.json`, which were transcribed from the build plan and carry `verify: true` (see `docs/KB_REVIEW.md`).',
  );
  lines.push('');
  return `${lines.join('\n')}`;
}
