#!/usr/bin/env node
/**
 * Copies the body of skills/passwerk/SKILL.md into src/chat/skill.ts so `passwerk chat`
 * and the skill cannot diverge (spec section 5). `test/skill.test.ts` fails when stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', '..');
const source = join(root, 'skills', 'passwerk', 'SKILL.md');
const target = join(here, '..', 'src', 'chat', 'skill.ts');

const md = readFileSync(source, 'utf8');
const body = md.replace(/^---\n[\s\S]*?\n---\n/, '').trim();

const out = [
  '// Generated by scripts/sync-skill.mjs from skills/passwerk/SKILL.md. Do not edit.',
  '// Regenerate with `pnpm --filter @passwerk/cli sync-skill`; test/skill.test.ts guards it.',
  `export const SKILL_TEXT = ${JSON.stringify(body)};`,
  '',
].join('\n');

writeFileSync(target, out);
console.log(`wrote ${target} (${body.length} chars)`);
